title:        API Management
url:          http://management.apievangelist.com
logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-management.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/blog/page:num"

org: api-evangelist
repo: management

# Masthead title
masthead_link: http://management.apievangelist.com
masthead_font_size: 90
masthead_title: '{"API Management"}'

# Feature
feature_title: API Guide
feature_link: http://apievangelist.com
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/api-guides-loading.jpg
feature_image_width: 45

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-tools.png
project_summary: This is a research project to stay in tune with the world of API management. This is the oldest area of my research, something I've been organizing since 2010. You can find news I've curated, organizations doing interesting things, some of the common building blocks I've identified, and open source tooling I've aggregated here in this research projects Github repository.

# Navigation
navigation:
  - label1: Home
    link1: /
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Blog
    link1: /blog/
    size1: 80
    extend: 1
    label2: RSS
    link2: /blog.xml
    size2: 60
    padding: 0
    decorate: 0
  - label1: News
    link1: /news/
    size1: 80
    extend: 1
    label2: RSS
    link2: /news.xml
    size2: 60
    padding: 0
    decorate: 0
  - label1: Organizations
    link1: /organizations/
    size1: 80
    extend: 1
    label2: JSON
    link2: /data/organizations.json
    size2: 60
    padding: 0
    decorate: 0
  - label1: Tools
    link1: /tools/
    size1: 80
    extend: 1
    label2: JSON
    link2: /data/tools.json
    size2: 60
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 0
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60

 curated
curated_desc:
curated_title: News I Have Curated
curated_desc: AAs I keep track on the world of APIs I curate news, blog posts, articles, and other research that I feel is relevant specifically to API management--these are the links I am including in my research.
curated_footer: If there is something you think should be listed here, <a href="https://github.com/{{ site.org }}/{{ site.repo }}/issues" target="_blank">you can submit as Github issue for this research project</a> and I will consider adding.

# Blog
blog_title: Blog Posts on API Management
blog_desc: These are posts from the API Evangelist blog that are focused on API management, allowing for a filtered look at my analysis on the topic. I rely on these posts, along with the curated, organizations, APIs, and tools to help paint me a picture of what is going on.
blog_footer: If there is an API management related story you'd like me to know about, <a href="https://github.com/{{ site.org }}/{{ site.repo }}/issues" target="_blank">you can submit as Github issue for this research project</a> and I will consider adding as part of my research.

# organizations
org_title: Some Organizations To Watch
org_desc: As I keep track on the world of APIs and read through the information I am curating I keep an eye out for any company, institution, or other agency that is doing anything interesting with API management. These are the organizations I'm currently including in my API management research.
org_footer: If there is an organization you think should be listed here, <a href="https://github.com/{{ site.org }}/{{ site.repo }}/issues" target="_blank">you can submit as Github issue for this research project</a> and I will consider adding.

# tools
tools_title: API Management Tooling
tools_desc: These are the open source API management tooling that I am tracking on as part of my research, and can be used to help in the API management process.
tools_footer: If there is an open source tool that should be listed here, <a href="https://github.com/{{ site.org }}/{{ site.repo }}/issues">submit as a Github Issue, and I will consider adding</a>, if it is open source, and fits into this API design research.

# building blocks
building_block_title: API Management Building Blocks
building_block_desc: As I monitor the API space I am always on the hunt for the common building blocks that make up any area of my work--these are some of the common elements I have aggregated from across the world of API management.
building_block_footer: I am always adding to, and shifting my lists of the common building blocks as I evolve my understand of the space, and who is doing interesting things with API depoyment.

# patents
patent_title: API Management Patents
patent_desc: I have been tracking on API related patents for some years, trying to understand how APIs are being referenced in patents, and in some cases the focus of the patent. Here are the patents I've tagged as being DNS related from the companies who are doing interesting things with DNS APIs.
patent_footer: I tend to process the new patent filings and publications every couple of weeks. When ready I try to publish them along with my research.
